# Generated by Django 4.1.5 on 2023-05-15 11:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("workspaces", "0002_rename_content_list_description_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="List",
            new_name="TaskList",
        ),
    ]
